>compound 27
>formula C6N2O5
>parentmass 180.9892287310432
>ionization [M + H]+
>instrumentation Unknown (LCMS)
>source file:/Users/priya/Desktop/protocode/./mzmine2.33/sirius.mgf
>index 27
>quality NoMS1Peak,FewPeaks,LowIntensity,PoorlyExplained,PoorlyExplained
#filename ENL_1-10.mzXML;END_1-10.mzXML;LA_1-2.mzXML;Phytomonic_1-10.mzXML;bMCA_1-10.mzXML;CLA_1-2.mzXML;Oleic_1-10.mzXML;aMCA_1-10.mzXML;CA_1-10.mzXML;Ellaidic_acid_1-2.mzXML
#scans -1

>ms1merged
180.9892287310432 100.0

